// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/02/2025, 19.19.14
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/plugins/**/*.{js,ts,mjs}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/composables/**/*.{js,ts,mjs}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/utils/**/*.{js,ts,mjs}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/app.config.{js,ts,mjs}","D:/vue/Smartwatch-IOH-Monitoring-nuxtjs/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;